/**
 * ShaderComposer - Generates WGSL shaders from LayerRegistry
 *
 * Composes shaders at runtime based on registered layers.
 * Uses main-template.wgsl as base and injects layer blend calls.
 */

import type { LayerDeclaration, AdvectionConfig } from '../services/layer/layer-service';
import type { TParameter, TModel } from '../config/types';
import { getMainShaders, getPostShaders } from './shader-loader';
import { getParamMeta } from '../config/params-ecmwf_ifs';
import '../config/params-ncep_gfs025';

// Import shader modules
import commonCode from './shaders/common.wgsl?raw';
import projectionO1280Code from './shaders/projection-o1280.wgsl?raw';
import layerHelpersCode from './shaders/layer-helpers.wgsl?raw';
import sunAtmoCode from '../layers/sun/atmo.wgsl?raw';
import logoCode from './shaders/logo.wgsl?raw';
import mainTemplateCode from './shaders/main-template.wgsl?raw';
import sunPostCode from '../layers/sun/post.wgsl?raw';
import sunCode from '../layers/sun/sun.wgsl?raw';
import sunBlendCode from '../layers/sun/blend.wgsl?raw';

export interface ComposedShaders {
  main: string;
  post: string;
}

/** Generated param shader code */
interface GeneratedParamShader {
  bindings: string;   // @group(0) @binding(...) declarations
  samplers: string;   // sampleParam_X(cell) function code
}

/** Param binding configuration */
export interface ParamBindingConfig {
  param: string;
  model: TModel;
  index: number;
  bindingSlot0: number;
  bindingSlot1: number;
  categorical: boolean;  // true = nearest-neighbor temporal sampling
}

/** Active param registry - exported for globe-renderer to use */
export let activeParamBindings: ParamBindingConfig[] = [];

// Starting binding index for dynamic params (avoid conflicts with 0-21)
const PARAM_BINDING_START = 50;

// Map blend function names to their parameter signatures
const BLEND_SIGNATURES: Record<string, string> = {
  blendBasemap: '(color, hit.point)',
  blendBase: '(color, hit.point)',
  blendTemp: '(color, lat, lon)',
  blendRain: '(color, lat, lon)',
  blendSun: '(color, hit.point)',
};

export class ShaderComposer {
  private initialized = false;
  private mainShaders: Map<string, string> = new Map();
  private postShaders: Map<string, string> = new Map();

  /** Initialize with shader code from shader-loader */
  init(): void {
    if (this.initialized) return;
    this.mainShaders = getMainShaders();
    this.postShaders = getPostShaders();
    this.initialized = true;
  }

  /** Compose shader from layer declarations */
  compose(layers: LayerDeclaration[]): ComposedShaders {
    if (!this.initialized) {
      this.init();
    }

    const surfaceLayers = layers.filter(l =>
      l.blendFn &&
      l.pass !== 'geometry' &&
      l.type !== 'decoration' || l.id === 'earth'  // earth is decoration but renders on surface
    );
    const postLayers = layers.filter(l => l.postFn);

    const main = this.composeMain(surfaceLayers, layers);
    const post = this.composePost(postLayers, layers);

    return { main, post };
  }

  private composeMain(surfaceLayers: LayerDeclaration[], allLayers: LayerDeclaration[]): string {
    const parts: string[] = [];

    // 1. Layer index constants (must come before layer shaders that use them)
    const layerConstants = this.generateLayerConstants(allLayers);
    parts.push(layerConstants);

    // 2. Uniforms struct and helper functions (must come before layer shaders)
    parts.push(layerHelpersCode);

    // 3. Common utilities (ray-sphere intersection, constants)
    parts.push(sunAtmoCode);  // Atmosphere functions needed by other shaders
    parts.push(commonCode);
    parts.push(projectionO1280Code);  // O1280 Gaussian grid projection

    // 3. Logo shader
    parts.push(logoCode);

    // 3. Layer blend functions (sorted by render order)
    const sortedLayers = [...surfaceLayers].sort((a, b) => (a.order) - (b.order));
    for (const layer of sortedLayers) {
      const shaderCode = layer.isBuiltIn
        ? this.mainShaders.get(layer.id)!
        : layer.shaders!.main;
      if (shaderCode) {
        parts.push(`// --- Layer: ${layer.id} ---`);
        parts.push(shaderCode);
      }
    }

    // 4. Graticule shader (special - always included for back-side graticule logic)
    const graticuleShader = this.mainShaders.get('graticule');
    if (graticuleShader) {
      parts.push('// --- Layer: graticule ---');
      parts.push(graticuleShader);
    }

    // 5. Generate dynamic param bindings
    const paramShader = this.generateParamBindings(surfaceLayers);

    // 6. Main template with blend calls and param bindings injected
    // Note: Layer constants are injected at the beginning of the shader (step 1)
    const blendCalls = this.generateBlendCalls(sortedLayers);
    const mainCode = mainTemplateCode
      .replace('// {{SURFACE_BLEND_CALLS}} - replaced by ShaderComposer', blendCalls)
      .replace('// {{PARAM_BINDINGS}} - Dynamic param buffer bindings (generated by ShaderComposer)', paramShader.bindings)
      .replace('// {{PARAM_SAMPLERS}} - Dynamic param sampler functions (generated by ShaderComposer)', paramShader.samplers)
      .replace('// {{LAYER_CONSTANTS}} - Layer index constants (generated by ShaderComposer)', '// (layer constants at top of shader)');
    parts.push(mainCode);

    return parts.join('\n\n');
  }

  private composePost(_postLayers: LayerDeclaration[], allLayers: LayerDeclaration[]): string {
    const parts: string[] = [];

    // 1. Layer index constants (LAYER_SUN needed for atmosphere blend)
    const layerConstants = this.generateLayerConstants(allLayers);
    parts.push(layerConstants);

    // 2. Uniforms struct and helpers (from layer-helpers.wgsl)
    parts.push(layerHelpersCode);

    // Atmosphere functions
    parts.push(sunAtmoCode);

    // Common utilities
    parts.push(commonCode);

    // Sun shader (for atmosphere constants)
    parts.push(sunCode);

    // Sun blend functions (blendAtmosphereSpace, blendAtmosphereGlobe)
    parts.push(sunBlendCode);

    // Post-process main shader
    parts.push(sunPostCode);

    return parts.join('\n\n');
  }

  /** Generate dynamic param bindings and sampler functions */
  private generateParamBindings(layers: LayerDeclaration[]): GeneratedParamShader {
    // 1. Collect unique params from all layers (with model)
    const allParams = new Map<TParameter, TModel>();
    for (const layer of layers) {
      layer.params?.forEach(ref => {
        if (!allParams.has(ref.param)) {
          allParams.set(ref.param, ref.model);
        }
      });
    }

    if (allParams.size === 0) {
      activeParamBindings = [];
      return { bindings: '// No dynamic params', samplers: '// No param samplers' };
    }

    // 2. Assign indices (stable ordering by param name)
    const paramList = [...allParams.entries()].sort((a, b) => a[0].localeCompare(b[0]));
    const paramConfigs: ParamBindingConfig[] = paramList.map(([param, model], idx) => ({
      param,
      model,
      index: idx,
      bindingSlot0: PARAM_BINDING_START + idx * 2,
      bindingSlot1: PARAM_BINDING_START + idx * 2 + 1,
      categorical: getParamMeta(param).categorical ?? false,
    }));

    // Export for globe-renderer to use
    activeParamBindings = paramConfigs;

    // 3. Generate binding declarations
    const bindings: string[] = ['// --- Dynamic param bindings (generated) ---'];
    for (const cfg of paramConfigs) {
      const safeName = cfg.param.replace(/[^a-zA-Z0-9]/g, '_');
      bindings.push(
        `@group(0) @binding(${cfg.bindingSlot0}) var<storage, read> param_${safeName}_0: array<f32>;`,
        `@group(0) @binding(${cfg.bindingSlot1}) var<storage, read> param_${safeName}_1: array<f32>;`
      );
    }

    // 4. Collect advection targets (params that get wind-displaced sampling)
    const advectionTargets = new Map<string, AdvectionConfig>();
    for (const layer of layers) {
      if (layer.advection) {
        for (const target of layer.advection.targets) {
          advectionTargets.set(target.param, layer.advection);
        }
      }
    }

    // 5. Generate sampler functions (model-aware, advection-aware)
    //    Wind samplers first (advected samplers call them)
    const samplers: string[] = ['// --- Param samplers (generated) ---'];
    const advectedSamplers: string[] = [];

    for (const cfg of paramConfigs) {
      const safeName = cfg.param.replace(/[^a-zA-Z0-9]/g, '_');
      const advection = advectionTargets.get(cfg.param);

      if (advection) {
        // Advected O1280 param — sampler takes (lat, lon), displaces by wind
        const uSafe = advection.uParam.param.replace(/[^a-zA-Z0-9]/g, '_');
        const vSafe = advection.vParam.param.replace(/[^a-zA-Z0-9]/g, '_');
        const sample = cfg.categorical
          ? `select(v0, v1, lerp >= 0.5)`
          : `mix(v0, v1, lerp)`;
        advectedSamplers.push(`
fn sampleParam_${safeName}(lat: f32, lon: f32) -> f32 {
  if (!isParamReady(${cfg.index}u)) { return 0.0; }
  let lerp = getParamLerp(${cfg.index}u);
  // Advection wind at current position (time-interpolated)
  let windU = sampleParam_${uSafe}(lat, lon);
  let windV = sampleParam_${vSafe}(lat, lon);
  // Displacement in radians (param's own t1-t0 spacing)
  let dt = getParamDt(${cfg.index}u);
  let R = 6371000.0;
  let cosLat = max(cos(lat), 0.01);
  let dlat = (windV * dt) / R;
  let dlon = (windU * dt) / (R * cosLat);
  // Backward trajectory: where was t0 air?
  let cell0 = o1280LatLonToCell(lat - dlat * lerp, lon - dlon * lerp);
  let v0 = param_${safeName}_0[cell0];
  // Forward trajectory: where will t1 air be?
  let cell1 = o1280LatLonToCell(lat + dlat * (1.0 - lerp), lon + dlon * (1.0 - lerp));
  let v1 = param_${safeName}_1[cell1];
  return ${sample};
}`);
      } else if (cfg.model === 'ncep_gfs025') {
        // Regular 0.25° grid (721 lat × 1440 lon) — sampler takes (lat, lon)
        const sample = cfg.categorical
          ? `select(v0, v1, lerp >= 0.5)`
          : `select(v0, mix(v0, v1, lerp), lerp >= 0.0)`;
        samplers.push(`
fn sampleParam_${safeName}(lat: f32, lon: f32) -> f32 {
  if (!isParamReady(${cfg.index}u)) { return 0.0; }
  let latF = (COMMON_PI * 0.5 - lat) * (720.0 / COMMON_PI);
  let lonWrap = lon - floor(lon / COMMON_TAU) * COMMON_TAU;
  let lonF = lonWrap * (1440.0 / COMMON_TAU);
  let latIdx = clamp(u32(latF), 0u, 720u);
  let lonIdx = u32(lonF) % 1440u;
  let cell = latIdx * 1440u + lonIdx;
  let v0 = param_${safeName}_0[cell];
  let v1 = param_${safeName}_1[cell];
  let lerp = getParamLerp(${cfg.index}u);
  return ${sample};
}`);
      } else {
        // O1280 grid — sampler takes cell index
        const sample = cfg.categorical
          ? `select(v0, v1, lerp >= 0.5)`
          : `select(v0, mix(v0, v1, lerp), lerp >= 0.0)`;
        samplers.push(`
fn sampleParam_${safeName}(cell: u32) -> f32 {
  if (!isParamReady(${cfg.index}u)) { return 0.0; }
  let v0 = param_${safeName}_0[cell];
  let v1 = param_${safeName}_1[cell];
  let lerp = getParamLerp(${cfg.index}u);
  return ${sample};
}`);
      }
    }

    // Advected samplers after wind samplers (dependency order)
    samplers.push(...advectedSamplers);

    return {
      bindings: bindings.join('\n'),
      samplers: samplers.join('\n'),
    };
  }

  /** Generate layer index constants (LAYER_EARTH = 0u, etc.) */
  private generateLayerConstants(layers: LayerDeclaration[]): string {
    const constants: string[] = ['// --- Layer index constants (generated) ---'];

    for (const layer of layers) {
      if (layer.index !== undefined) {
        const name = layer.id.toUpperCase().replace(/[^A-Z0-9]/g, '_');
        constants.push(`const LAYER_${name}: u32 = ${layer.index}u;`);
      }
    }

    if (constants.length === 1) {
      return '// No layer constants';
    }

    return constants.join('\n');
  }

  private generateBlendCalls(layers: LayerDeclaration[]): string {
    const calls: string[] = [];

    for (const layer of layers) {
      const blendFn = layer.blendFn!;
      const signature = layer.isBuiltIn
        ? BLEND_SIGNATURES[blendFn]!
        : '(color, lat, lon)';
      const call = `color = ${blendFn}${signature};`;

      // Earth basemap always renders (it's the base layer)
      if (layer.id === 'earth') {
        calls.push(`  ${call}`);
      } else if (layer.isBuiltIn) {
        const name = layer.id.toUpperCase().replace(/[^A-Z0-9]/g, '_');
        let guard = `getLayerOpacity(LAYER_${name}) > 0.0`;
        // Advected layers: gate on wind param readiness (avoid rendering without displacement)
        if (layer.advection) {
          const uIdx = activeParamBindings.findIndex(p => p.param === layer.advection!.uParam.param);
          const vIdx = activeParamBindings.findIndex(p => p.param === layer.advection!.vParam.param);
          if (uIdx >= 0) guard += ` && isParamReady(${uIdx}u)`;
          if (vIdx >= 0) guard += ` && isParamReady(${vIdx}u)`;
        }
        calls.push(`  if (${guard}) { ${call} }`);
      } else {
        calls.push(`  if (getUserLayerOpacity(${layer.userLayerIndex!}u) > 0.0) { ${call} }`);
      }
    }

    if (calls.length === 0) {
      return '  // No surface layers enabled';
    }

    return calls.join('\n');
  }

  /** Check if layer has main shader code available */
  hasLayerShader(layerId: string): boolean {
    return this.mainShaders.has(layerId);
  }

  /** Check if layer has post shader code available */
  hasPostShader(layerId: string): boolean {
    return this.postShaders.has(layerId);
  }
}

/** Singleton instance */
export const shaderComposer = new ShaderComposer();
