import { test, expect } from '@playwright/test';
import { testLayerPixels, waitForAppReady, waitForLayerReady, readCenterPixel } from '../helpers';

// Deterministic pixel tests with injected data
// .bin files generated by: python tests/scripts/generate_test_bins.py
testLayerPixels('temp', [
  { fixture: 'uniform-55', palette: 'Classic Temperature', baseRgb: [107, 28, 43] },
  { fixture: 'uniform-minus20', palette: 'Classic Temperature', baseRgb: [143, 168, 184] },
  // Test opacity blending
  { fixture: 'uniform-55', palette: 'Classic Temperature', baseRgb: [107, 28, 43], opacities: [0.5] },
]);

// Toggle and persistence tests (use live data)
test.describe('temp.enabled', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/');
    await waitForAppReady(page);
  });

  test('toggle on shows temperature layer', async ({ page }) => {
    await page.evaluate(() => {
      (window as any).__hypatia.optionsService.update((d: any) => {
        d.earth.enabled = true;
        d.temp.enabled = true;
        d.temp.opacity = 1.0;
      });
    });

    await waitForLayerReady(page, 'temp');
    await page.waitForTimeout(500);

    const pixel = await readCenterPixel(page);
    const isBackground = pixel.r === 22 && pixel.g === 22 && pixel.b === 22;
    expect(isBackground).toBe(false);
  });

  test('toggle off hides temperature layer', async ({ page }) => {
    await page.evaluate(() => {
      (window as any).__hypatia.optionsService.update((d: any) => {
        d.earth.enabled = true;
        d.temp.enabled = true;
        d.temp.opacity = 1.0;
      });
    });
    await waitForLayerReady(page, 'temp');
    await page.waitForTimeout(500);

    const pixelOn = await readCenterPixel(page);

    await page.evaluate(() => {
      (window as any).__hypatia.optionsService.update((d: any) => {
        d.temp.enabled = false;
      });
    });
    await page.waitForTimeout(500);

    const pixelOff = await readCenterPixel(page);
    const changed = pixelOn.r !== pixelOff.r || pixelOn.g !== pixelOff.g || pixelOn.b !== pixelOff.b;
    expect(changed).toBe(true);
  });

  test('temp.enabled persists after reload', async ({ page }) => {
    await page.evaluate(() => {
      (window as any).__hypatia.optionsService.update((d: any) => {
        d.temp.enabled = true;
      });
    });

    const enabledBefore = await page.evaluate(() =>
      (window as any).__hypatia.optionsService.options.value.temp.enabled
    );
    expect(enabledBefore).toBe(true);

    await page.reload();
    await waitForAppReady(page);

    const enabledAfter = await page.evaluate(() =>
      (window as any).__hypatia.optionsService.options.value.temp.enabled
    );
    expect(enabledAfter).toBe(true);
  });
});
